### ISSUE TITLE
S3FS: Volume mounting fails outside us-east-1

### ISSUE THREAD

**Issue by FranciscoDA** [marcelo-ochoa/docker-volume-plugins#12]
**Describe the bug**
When mounting a volume that references an S3 bucket outside of the AWS us-east-1 region, the container initialization fails.

**To Reproduce**
1. Create an AWS bucket in a region outside of us-east-1 (e.g: ap-northeast-1). Create a subdirectory for kicks
2. Configure plugin with credentials: `docker plugin enable mochoa/s3fs-volume-plugin:latest AWSACCESSKEYID=<keyid> AWSSECRETACCESSKEY=<secret> --grant-all-permissions`
3. Create volume and service:
```
volumes:
  myvol:
    driver: mochoa/s3fs-volume-plugin:latest
    name: "mybucket/mysubdir"

services:
  ubuntu:
    image: ubuntu:latest
    volumes:
      - myvol:/mybucket
```
4. Initialize container: `docker-compose run --rm ubuntu bash`
5. Container creation fails:
```
$ docker-compose run --rm ubuntu bash
[+] Running 1/0
 ⠿ Volume "myvol/mysubdir"  Created                                                                                                                                       0.0s
Error response from daemon: error while mounting volume '': VolumeDriver.Mount: error mounting myvol/mysubdir:
df: /var/lib/docker-volumes/<volumehash>: Software caused connection abort

fstype should be s3fs
```

**Expected behavior**
The volume should be mounted correctly inside the container

**Server (please complete the following information):**
 - OS: Arch linux

**Additional context**
logs from `journalctl -f -u docker.service`:
```
May 26 00:36:15 SWIFT dockerd[74543]: time="2022-05-26T00:36:15-03:00" level=error msg="2022/05/26 03:36:15 [/var/lib/docker-volumes/93fc9e5c754fcea78015467b7aa6341a034cdce9465cff3bbfd618c1d60f4412 -o nomultipart,bucket=mybucket:/mysubdir]" plugin=b89c599f4771fb877bbbfd08746965a044a36fe6c7c7d9ee08b81532bf762dc5
May 26 00:36:19 SWIFT dockerd[74543]: time="2022-05-26T00:36:19-03:00" level=info msg="df --output=fstype: df: /var/lib/docker-volumes/93fc9e5c754fcea78015467b7aa6341a034cdce9465cff3bbfd618c1d60f4412: Software caused connection abort" plugin=b89c599f4771fb877bbbfd08746965a044a36fe6c7c7d9ee08b81532bf762dc5
```

**Comment by ovangle** [comment]
@FransiscoDA
I am experiencing the same problem and was trying to get your fix working...

It has let me create a volume which points to the root of the bucket, e.g.

```yaml
volumes:
  s3-volume:
     driver: s3fs
     name: s3-volume-name
```
Works ok and I can mount the volumeproperly in a temporary container

however I'm still encountering errors when attempting to mount a subdirectory of the volume

```yaml
volumes:
   s3-volume-subdir:
      driver: s3fs
      name: s3-volume-name/service/path
 ````
 
 Gives same `fstype should be s3fs` error.

`docker volume inspect s3-volume-name/service/path | jq '.[].Status.args'` gives the following output:

```json
  [
    "-o",
    "nomultipart,url=https://ap-south-1.linodeobjects.com,bucket=s3-volume-name:/service/path"
  ]
```

I think `servicepath` should be provided as a separate option (i.e. `bucket=s3-bucket-name,servicepath=/service/path`)? From `man s3fs` 

```
    -o sevicepath (default="/")
              Set a service path when the non-Amazon host requires a prefix.
```

**Comment by ovangle** [comment]
Sorry, my bad. `/service/path` did not exist on remote.

**Comment by vpithan** [comment]
> Sorry, my bad. `/service/path` did not exist on remote.

I had the same problem. Thank you so much.

I created the subpath on my bucket and the error gones.

**Comment by vpithan** [comment]
@FranciscoDA please, try to add this env `DEFAULT_S3FSOPTS="url=https://s3.ap-northeast-1.amazonaws.com/"` into plugin setup.

Or with swarm:

```yml
volumes:
  myvol:
    driver: mochoa/s3fs-volume-plugin:latest
    driver_opts:
      s3fsopts: "url=https://s3.ap-northeast-1.amazonaws.com/"
    name: "mybucket/mysubdir"
```

Make sure that your subpath exists into bucket.
