### ISSUE TITLE
Additional property name is not allowed

### ISSUE THREAD

**Issue by ggogel** [marcelo-ochoa/docker-volume-plugins#3]
**Describe the bug**
I'm simply trying to use this plugin to mount a glusterfs volume. I configured my compose file exactly as described in the documentation
```
volumes:
  jellyfin-data:
    driver: glusterfs
    name: "swarm-volumes/jellyfin-beta_jellyfin-data"
```
After running docker stack deploy it throws this error:
`volumes.jellyfin-data Additional property name is not allowed`

**To Reproduce**
1. Install plugin
2. Add volume to compose file
3. docker stack deploy

**Expected behavior**
The stack should be deployed and volume mounted without error.

**Server (please complete the following information):**
 - OS: CentOs Stream
 - GlusterFs 8.3
 - Docker version 20.10.2, build 2291f61
