### ISSUE TITLE
cifs plugin naming issue

### ISSUE THREAD

**Issue by ggogel** [marcelo-ochoa/docker-volume-plugins#4]
**Describe the bug**
I'm trying to use the cifs plugin with Docker Swarm. The issue seems to be that the plugin is naming the volumes according to the variable `volumes.volume-name.name`. From my understanding the variable `volumes.volume-name.name` should represent the cifs path, e.g. `fileserver/share`, and the name should be taken from `volumes.volume-name` but this is not the case. The problem is if the plugin names the volume `fileserver/share`, I can't mount it within a service / container because docker thinks this is a host path. Volume names are not allowed to contain `/`. 

**To Reproduce**
1. Create the credentials file /root/credentials/file01 
2. Create a docker compose with:
```
services:
  servicename: ...
  volumes:
     - type: volume
        source: 'file01d'
        target: '/mnt/smbdata'

volumes:
  file01d:
    driver: cifs
    name: "file01/d"

```
2. run `docker stack deploy`
3. Check the container and see the error that it can't mount `file01d`

**Expected behavior**
Volume should be named `file01d` instead of `file01/d`

**Server (please complete the following information):**
 - OS: CentOS Stream
 - Version: latest
