### ISSUE TITLE
Cannot create docker volume

### ISSUE THREAD

**Issue by Rihan9** [marcelo-ochoa/docker-volume-plugins#8]
**Describe the bug**
Hi,
I have a system with 2 nodes (the third is on the way) both with glusterfs ad docker swarm configurated.
I have 1 gluster volume online, named "gfs" with some subfolders like "nginx-proxy-manager" (i use this as example below).

I can mount this folder with the command:
`sudo glusterfs --volfile-server=localhost --volfile-id=gfs --subdir-mount=/nginx-proxy-manager ./test`
and the following command run without error:
`docker volume create -d glusterfs --opt "glusteropts=--volfile-server=localhost --volfile-id=gfs --subdir-mount=/nginx-proxy-manager" test`

BUT:
The services that use this volume can't run:

```
VolumeDriver.Mount: error mounting sh_gfs_nginx-proxy-manager: df: /var/lib/docker-volumes/0a20292622d3ced85dba291fd7491f2b953cc14c7c6c79771e0e7cfbdf38b287: Transport endpoint is not connected fstype should be glusterfs
```

the volume on sh.yaml file of the cluster is configurated with the following line:
```
gfs_nginx-proxy-manager: 
  driver: glusterfs
  driver_opts:
    glusteropts: "--volfile-server=localhost --volfile-id=gfs --subdir-mount=/nginx-proxy-manager"
```

what am I doing wrong? 

**Server (please complete the following information):**
 - OS: Raspberry OS 
 - Version 10.9
 - Docker version: 20.10.7, build f0df350
 - Plugin version: latest, installed with the following command today 06/11:
 `docker plugin install --alias glusterfs mochoa/glusterfs-volume-plugin-armv7l --grant-all-permissions --disable`
- Glusterfs server version: glusterfs 5.5
